---
# A component which allows you to track and update custom cards/components
# and python_scripts.
#
# https://github.com/custom-components/custom_updater
#
custom_updater:
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
