#################################################################
#                                                               #
#                      Packages/Weather                         #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
    sensor.season:
      friendly_name: Seizoen
    sensor.pws_observation_time:   
      friendly_name: Laatst bijgewerkt
    sensor.pws_location:
      friendly_name: Locatie
    sensor.pws_station_id:
      friendly_name: Weerstation
    sensor.pws_weather:
      friendly_name: Weer 
    sensor.pws_temp_c:
      friendly_name: Temperatuur
    sensor.pws_temp_f:
      friendly_name: Temperatuur (F)
    sensor.pws_feelslike_string:
      friendly_name: Gevoelstemperatuur
      icon: mdi:thermometer
    sensor.pws_heat_index_string:
      friendly_name: Heat Index
      icon: mdi:thermometer
    sensor.pws_relative_humidity:
      friendly_name: Luchtvochtigheid
      icon: mdi:weather-rainy
    sensor.pws_dewpoint_string:
      friendly_name: Dauwpunt
      icon: mdi:weather-rainy
    sensor.pws_wind_string:
      friendly_name: Wind
      icon: mdi:weather-windy
    sensor.pws_precip_today_string:
      friendly_name: Neerslag
    sensor.pws_pressure_in:
      friendly_name: Luchtdruk
    sensor.pws_visibility_mi:
      friendly_name: Zicht
    sensor.pws_uv:
      friendly_name: UV
      icon: mdi:weather-sunny
    sensor.pws_solarradiation:
      friendly_name: Zonne straling
      icon: mdi:weather-sunny
    sensor.pws_dewpoint_c:
      friendly_name: Dauwpunt
    sensor.pws_dewpoint_f:
      friendly_name: Dauwpunt (F)
    sensor.pws_feelslike_c:
      friendly_name: Voelt als
    sensor.pws_feelslike_f:
      friendly_name: Voelt als (F)
    sensor.pws_heat_index_c:
      friendly_name: Heat Index (C)
    sensor.pws_heat_index_f:
      friendly_name: Heat Index (F)
    sensor.pws_precip_today_in:
      friendly_name: Neerslag (in)
    sensor.pws_precip_today_metric:
      friendly_name: Neerslag (mm)
      icon: mdi:weather-rainy
    sensor.pws_pressure_mb:
      friendly_name: Luchtdruk (mb)
      icon: mdi:thermometer-lines
    sensor.pws_visibility_km:
      friendly_name: Zicht
    sensor.pws_wind_dir:
      friendly_name: Wind Richting
    sensor.pws_wind_kph:
      friendly_name: Wind snelheid (km/u)
      icon: mdi:weather-windy
    sensor.pws_wind_mph:
      friendly_name: Wind snelheid (mph)
    sensor.pws_alerts:
      friendly_name: Gevaarlijk weer
      icon: mdi:alert-outline

#################################################################
#                                                               #
#                           Group                               #
#                                                               #
#################################################################




#################################################################
#                                                               #
#                            Sensors                            #
#                                                               #
#################################################################

sensor:
  - platform: mqtt
    state_topic: "phone/lgcoca"
    name: "Light level"
    unit_of_measurement: "lx"
    value_template: '{{ value_json.lux }}'
    device_class: illuminance
    
  - platform: time_date
    display_options:
      - time
      - date
      - time_date
      - beat
      
  - platform: season
## Darksky weather sensor  
  - platform: darksky
    api_key: !secret darksky_api
    monitored_conditions:
#      - icon
      - summary
      - temperature
      - humidity
      - wind_speed
      - wind_bearing
      - cloud_cover
      - precip_probability
      - precip_type
      - precip_intensity
      - daily_summary
## Wunderground weather sensor
  - platform: wunderground
    api_key: 0309147472deddca
    lang: NL
    monitored_conditions:
      - weather
      - alerts
      - dewpoint_c
      - feelslike_c
      - location
      - observation_time
      - precip_1hr_metric
      - precip_today_metric
      - pressure_mb
      - pressure_trend
      - relative_humidity
      - station_id
      - solarradiation
      - temp_c
      - UV
      - visibility_km
      - weather_1d_metric
      - weather_1n_metric
      - weather_2d_metric
      - weather_2n_metric
      - weather_3d_metric
      - weather_3n_metric
      - wind_degrees
      - wind_dir
      - wind_gust_kph
      - wind_kph
  - platform: buienradar
    monitored_conditions:
      - symbol
      - humidity
      - temperature
      - windspeed
      - pressure
      - precipitation_forecast_total 
  - platform: template
    sensors:
## Period of the day
      period_of_day:
        friendly_name: 'Periode van de dag'
        value_template: >-
          {% if (as_timestamp(states.sun.sun.attributes.next_dusk)) - (as_timestamp(states.sun.sun.attributes.next_setting)) < 0 %}
            schemer
          {% elif (as_timestamp(states.sun.sun.attributes.next_rising)) - (as_timestamp(states.sun.sun.attributes.next_dawn)) < 0 %}
            zonsopgang
          {% elif (states.sun.sun.attributes.elevation) < 0 %}
            nacht
          {% else %}
            dag
          {% endif %}
        icon_template: >-
          {% if is_state('sun.sun', 'above_horizon') %}
            mdi:weather-sunny
          {% else %}
            mdi:weather-night
          {% endif %}
## Daylight
      sunlight:
        friendly_name: Zonlicht
        unit_of_measurement: "lx"
        value_template: '{{ "%.2f"|format((states.sun.sun.attributes.elevation/7) * (states.sun.sun.attributes.elevation|abs/7) + (1-(states.sensor.dark_sky_cloud_coverage.state|int/100))) }}'
        device_class: illuminance
      clouds:
        friendly_name: Bewolking
        unit_of_measurement: "%"
        value_template: '{{ states.sensor.dark_sky_cloud_coverage.state }}'
  - platform: template
    sensors:
      sun_elevation:
        friendly_name: Sun Elevation
        value_template: '{{states.sun.sun.attributes.elevation}}'
        unit_of_measurement: '°'
####################################################
#                                                  #
#                     Weather                      #
#                                                  #
####################################################

sun:

weather:
  - platform: buienradar
    name: 'rozenburg'
    latitude: 51.98
    longitude: 4.10
    forecast: True
    
  - platform: yweather  
  - platform: darksky
    api_key: !secret darksky_api
    #language: nl

####################################################
#                                                  #
#                      Camera                      #
#                                                  #
####################################################

camera:
  - platform: generic
    still_image_url: https://cdn.knmi.nl/knmi/map/general/weather-map.gif?62809862ee43b59a9bc9bcda6b0288cd
    name: knmi_buienradar
  - platform: generic
    still_image_url: https://cdn.knmi.nl/knmi/map/current/weather/forecast/kaart_verwachtingen_Vandaag_dag.gif?a20c6b28eba3982f8a63cad331ab3960 
    name: knmi_verwachting_vandaag
  - platform: generic
    still_image_url: https://cdn.knmi.nl/knmi/map/current/weather/forecast/kaart_verwachtingen_Morgen_nacht.gif?a20c6b28eba3982f8a63cad331ab3960
    name: knmi_verwachting_komende_nacht
  - platform: generic
    still_image_url: https://cdn.knmi.nl/knmi/map/current/weather/forecast/kaart_verwachtingen_Morgen_dag.gif?a20c6b28eba3982f8a63cad331ab3960
    name: knmi_verwachting_morgen
