hyperion_effect:
  name: Hyperion Effect
  options:
   - "Knight Rider"
   - "Mood Blobs Blue"
   - "Mood Blobs Cold"
   - "Mood Blobs Full Color"
   - "Mood Blobs Green"
   - "Mood Blobs Rainbow"
   - "Mood Blobs Red"
   - "Mood Blobs Warm"
   - "On"
   - "Off"
   - "Rainbow Swirl"
   - "Snake"
   - "Strobe Blue"
   - "Strobe Raspberry"
   - "Strobe White"
   - "Cinema Dim Lights"
   - "Cinema Brighten Lights"
   - "Police Lights Single"
   - "Police Lights Solid"
   - "Random"
   - "Running Dots"
   - "System Shutdown"
   - "Sparks Color"
   - "Sparks"
   - "Color Traces"
  initial: "Off"
