alias: "Going Sleeping"
initial_state: 'on'
trigger:
  - platform: state
    entity_id: light.woonkamer
    to: 'off'
  - platform: mqtt
    topic: 'milight/updates/0x2294/rgb_cct/0'
    payload: '{"state":"OFF"}'
condition:
  - condition: or
    conditions:
      - condition: time
        after: '22:00:00'
      - condition: time
        before: '6:00:00'
action:
  - service: switch.turn_on
    data:
      entity_id: switch.sleeping 
