# set the minutes of the alarm clock
alias: set alarmclock minutes
initial_state: 'on'
trigger:
  platform: mqtt
  topic: home/alarm/time/minute
action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.alarm_clock_minutes
      value: '{{ trigger.payload}}'
