  # Time to wake up
alias: Wakeup Time
initial_state: 'on'
trigger:
  platform: template
  value_template: '{{ states.sensor.time.state == states.sensor.alarm_clock_time.state }}'
action:
  - service: persistent_notification.create
    data:
      message: "tijd om op te staan"
      title: "Wakker worden"
  - service: homeassistant.turn_off
    data:
      entity_id: switch.sleeping
