alias: Spot Brightness Set
initial_state: 'on'
trigger:
  platform: state 
  entity_id: input_number.spot_bank
action:  
  service: light.turn_on 
  entity_id: light.spot
  data_template:   
    brightness: '{{ states( "input_number.brightness_spot" )|round( 0 ) }}'
