alias: Bank Brightness Set
id: "156754987"
initial_state: 'on'
trigger:
  platform: state 
  entity_id: input_number.brightness_bank
action:  
  service: light.turn_on 
  entity_id: light.bank
  data_template:   
    brightness: '{{ states( "input_number.brightness_bank" )|round( 0 ) }}'
