alias: Milight remote Fix
initial_state: True
trigger:
  - platform: mqtt
    topic: 'milight/updates/0x2294/rgb_cct/0'
action:
  - service: mqtt.publish
    data_template:
      topic: 'milight/0x2294/rgb_cct/1'
      payload_template: '{{ trigger.payload }}'
  - service: mqtt.publish
    data_template:
      topic: 'milight/0x2294/rgb_cct/2'
      payload_template: '{{ trigger.payload }}'
  - service: mqtt.publish
    data_template:
      topic: 'milight/0x2294/rgb_cct/3'
      payload_template: '{{ trigger.payload }}'
  - service: mqtt.publish
    data_template:
      topic: 'milight/0x2294/rgb_cct/4'
      payload_template: '{{ trigger.payload }}' 
