alias: spot Scenes
initial_state: 'on'
trigger:
  platform: state
  entity_id: input_select.scene_spot
action:
  - service: scene.turn_on
    data_template:
      entity_id: >
        {% if is_state("input_select.scene_spot", "Avond") %}
          scene.spot_avond
        {% elif is_state("input_select.scene_spot", "Lezen") %}
          scene.spot_lezen
        {% elif is_state("input_select.scene_spot", "Energie") %}
          scene.spot_energie
        {% endif %}
  - service: input_select.select_option
    data:
      entity_id: input_select.scene_spot
      option: "-"
