alias: "ambilight On"
initial_state: 'on'
trigger:
  - platform: state
    entity_id: light.woonkamer
    to: 'on'
  - platform: mqtt
    topic: 'milight/updates/0x2294/rgb_cct/0'
    payload: '{"state":"ON"}'
action:
  - service: light.turn_on
    data:
      entity_id: light.ambilight 
