platform: template
switches:
  partymode:
    value_template: '{% if is_state("media_player.baldr", "playing") %}on{% else %}off{% endif %}'
    turn_on:
      service: switch.turn_on
      data:
        entity_id: switch.kodi_party_mode
    turn_off:
      service: switch.turn_off
      data:
        entity_id: switch.kodi_party_mode
