platform: command_line
switches:
  pihole:
    command_on: !secret pihole_on
    command_off: !secret pihole_off
    command_state: !secret pihole_state
    value_template: "{{ value_json.status == 'enabled' }}" 
