platform: mqtt
name: "TV Slaapkamer"
state_topic: "stat/TV/POWER"
command_topic: "cmnd/TV/POWER"
availability_topic: "tele/TV/LWT"
payload_on: "ON"
payload_off: "OFF"
payload_available: "Online"
payload_not_available: "Offline"
icon: mdi:television 
