alias: "Cinema Brighten Lights"
hide_entity: True
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_select.hyperion_effect
    to: "Cinema Brighten Lights"
action:
  service: shell_command.h_cinema_brighten_lights 
