alias: "Color Traces"
hide_entity: True
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_select.hyperion_effect
    to: "Color Traces"
action:
  service: shell_command.h_color_traces
