alias: "Mood Blobs Full Color"
hide_entity: True
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_select.hyperion_effect
    to: "Mood Blobs Full Color"
action:
  service: shell_command.h_mood_blobs_full_color
