alias: "Mood Blobs Red"
hide_entity: True
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_select.hyperion_effect
    to: "Mood Blobs Red"
action:
  service: shell_command.h_mood_blobs_red
