alias: "Rainbow Swirl"
hide_entity: True
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_select.hyperion_effect
    to: "Rainbow Swirl"
action:
  service: shell_command.h_rainbow_swirl
