alias: "Running Dots"
hide_entity: True
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_select.hyperion_effect
    to: "Running Dots"
action:
  service: shell_command.h_running_dots
