alias: "Strobe Raspberry"
hide_entity: True
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_select.hyperion_effect
    to: "Strobe Raspberry"
action:
  service: shell_command.h_strobe_raspberry
