alias: "System Shutdown"
hide_entity: True
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_select.hyperion_effect
    to: "System Shutdown"
action:
  service: shell_command.h_system_shutdown
