  sensor.season:
    friendly_name: Seizoen
  sensor.pws_observation_time:   
    friendly_name: Laatst bijgewerkt
  sensor.pws_location:
    friendly_name: Locatie
  sensor.pws_station_id:
    friendly_name: Weerstation
  sensor.pws_weather:
    friendly_name: Weer 
  sensor.pws_temp_c:
    friendly_name: Temperatuur
  sensor.pws_temp_f:
    friendly_name: Temperatuur (F)
  sensor.pws_feelslike_string:
    friendly_name: Gevoelstemperatuur
    icon: mdi:thermometer
  sensor.pws_heat_index_string:
    friendly_name: Heat Index
    icon: mdi:thermometer
  sensor.pws_relative_humidity:
    friendly_name: Luchtvochtigheid
    icon: mdi:weather-rainy
  sensor.pws_dewpoint_string:
    friendly_name: Dauwpunt
    icon: mdi:weather-rainy
  sensor.pws_wind_string:
    friendly_name: Wind
    icon: mdi:weather-windy
  sensor.pws_precip_today_string:
    friendly_name: Neerslag
  sensor.pws_pressure_in:
    friendly_name: Luchtdruk
  sensor.pws_visibility_mi:
    friendly_name: Zicht
  sensor.pws_uv:
    friendly_name: UV
    icon: mdi:weather-sunny
  sensor.pws_solarradiation:
    friendly_name: Zonne straling
    icon: mdi:weather-sunny
  sensor.pws_dewpoint_c:
    friendly_name: Dauwpunt
  sensor.pws_dewpoint_f:
    friendly_name: Dauwpunt (F)
  sensor.pws_feelslike_c:
    friendly_name: Voelt als
  sensor.pws_feelslike_f:
    friendly_name: Voelt als (F)
  sensor.pws_heat_index_c:
    friendly_name: Heat Index (C)
  sensor.pws_heat_index_f:
    friendly_name: Heat Index (F)
  sensor.pws_precip_today_in:
    friendly_name: Neerslag (in)
  sensor.pws_precip_today_metric:
    friendly_name: Neerslag (mm)
    icon: mdi:weather-rainy
  sensor.pws_pressure_mb:
    friendly_name: Luchtdruk (mb)
    icon: mdi:thermometer-lines
  sensor.pws_visibility_km:
    friendly_name: Zicht
  sensor.pws_wind_dir:
    friendly_name: Wind Richting
  sensor.pws_wind_kph:
    friendly_name: Wind snelheid (km/u)
    icon: mdi:weather-windy
  sensor.pws_wind_mph:
    friendly_name: Wind snelheid (mph)
  sensor.pws_alerts:
    friendly_name: Gevaarlijk weer
    icon: mdi:alert-outline 
