alias: Iedereen weg
initial_state: 'on'
trigger:
  - platform: state
    entity_id: group.tracked_people
    to: not_home
action:
  - service: switch.turn_off
    data:
      entity_id: switch
  - service: shell_command.tasker_notify
    data:
      key: !secret tasker_key
      sender: !secret tasker_sender
      title: "Iedereen is weg"
      message: "Er is niemand thuis" 
