platform: template
sensors:
## Period of the day
  period_of_day:
    friendly_name: 'Periode van de dag'
    value_template: >-
      {% if (as_timestamp(states.sun.sun.attributes.next_dusk)) - (as_timestamp(states.sun.sun.attributes.next_setting)) < 0 %}
        schemer
      {% elif (as_timestamp(states.sun.sun.attributes.next_rising)) - (as_timestamp(states.sun.sun.attributes.next_dawn)) < 0 %}
        zonsopgang
      {% elif (states.sun.sun.attributes.elevation) < 0 %}
        nacht
      {% else %}
        dag
      {% endif %}
    icon_template: >-
      {% if is_state('sun.sun', 'above_horizon') %}
        mdi:weather-sunny
      {% else %}
        mdi:weather-night
      {% endif %} 
