  h_mood_blobs_blue: '../../scripts/effects.sh "Blue mood blobs"'
  h_mood_blobs_cold: '../../scripts/effects.sh "Cold mood blobs"'
  h_mood_blobs_full_color: '../../scripts/effects.sh "Full color mood blobs"'
  h_mood_blobs_green: '../../scripts/effects.sh "Green mood blobs"'
  h_mood_blobs_red: '../../scripts/effects.sh "Red mood blobs"'
  h_mood_blobs_warm: '../../scripts/effects.sh "Warm mood blobs"'
  h_rainbow_mood: '../../scripts/effects.sh "Rainbow mood"'
  h_rainbow_swirl: '../../scripts/effects.sh "Rainbow swirl fast"'
  h_snake: '../../scripts/effects.sh "Snake"'
  h_strobe_blue: '../../scripts/effects.sh "Strobe blue"'
  h_hyperion_on: '../../scripts/hyperionon.sh'
  h_hyperion_off: '../../scripts/hyperionoff.sh'
  h_strobe_raspberry: '../../scripts/effects.sh "Strobe Raspbmc"'
  h_strobe_white: '../../scripts/effects.sh "Strobe white"'
  h_cinema_dim_lights: '../../scripts/effects.sh "Cinema dim lights"'
  h_cinema_brighten_lights: '../../scripts/effects.sh "Cinema brighten lights"'
  h_police_lights_single: '../../scripts/effects.sh "Police Lights Single"'
  h_police_lights_solid: '../../scripts/effects.sh "Police Lights Solid"'
  h_random: '../../scripts/effects.sh "Random"'
  h_running_dots: '../../scripts/effects.sh "Running dots"'
  h_system_shutdown: '../../scripts/effects.sh "System Shutdown"'
  h_sparks_color: '../../scripts/effects.sh "Sparks Color"'
  h_sparks: '../../scripts/effects.sh "Sparks"'
  h_color_traces: '../../scripts/effects.sh "Color traces"'
